#%RAML 1.0 DataType
title: 'Erro nos parâmetros informados'
type: object
properties:
  results:
    type: string
    description: 'String vazia'
  status: 
    type: string
    description: 'Status da requisicao'